name: Tests

on: [push, pull_request]

jobs:
  run-tests:

    runs-on: ubuntu-latest
    strategy:
        matrix:
            php-versions: ['8.0', '8.1']
    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
           php-version: ${{ matrix.php-versions }}
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Install pupeteer
      run:  sudo npm install --global --unsafe-perm puppeteer
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit
